// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkdovbbczvmgavtvklki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZG92YmJjenZtZ2F2dHZrbGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTY5NDIsImV4cCI6MjA2Mjk5Mjk0Mn0.dlD7REhvR67XcNEJEl3nX0eK0gUh9ImkUMlx8s6IWWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);